1. Create a 1D NumPy array of integers from 0 to 9.

In [1]:
import numpy as np
arr =np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


2. Create a 2D NumPy array with shape (3, 3) filled with zeros.

In [2]:
arr =np.array([[0,0,0],[0,0,0],[0,0,0]])
print(arr)
print(arr.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


3. Create a 3x3 identity matrix using NumPy.

In [3]:
arr =np.array([[1,0,0],[0,1,0],[0,0,1]])
print(arr)
print(arr.shape)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
(3, 3)


4. Create a 1D NumPy array with five elements, all initialized to 10.

In [ ]:
arr =np.array([10,10,10,10,10])
print(arr)
print(arr.shape)

5. Generate a random 2x3 array of floats between 0 and 1.

In [19]:
arr = np.random.uniform(0,1,size=(2,3))
print(arr)

[[0.75479551 0.70357677 0.49321925]
 [0.44070534 0.21884555 0.86980462]]


6. Reshape the array from question 5 into a 3x2 array.

In [22]:
narr=arr.reshape(3, 2)
print(narr)

[[0.75479551 0.70357677]
 [0.49321925 0.44070534]
 [0.21884555 0.86980462]]


7. Find the maximum value in an array of integers from 1 to 10.

In [32]:
arr =np.array([1,2,3,4,5,6,7,8,9,10])
print(max(arr))

10


8. Find the mean of a 1D array of numbers from 1 to 5.

In [33]:
arr =np.array([1,2,3,4,5])
print(np.mean(arr))

3.0


9. Perform element-wise addition of two NumPy arrays of the same shape.

In [34]:
arr =np.array([1,3,5,7,4])
narr =np.array([3,56,3,3,2])
print(arr+narr)

[ 4 59  8 10  6]


10. Compute the dot product of two 1D arrays of the same length.

In [38]:
arr =np.array([1,-1])
narr =np.array([1,1])
print(sum(arr*narr))

0


11. Reshape a 1D array of integers from 1 to 12 into a 3x4 matrix.

In [39]:
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
narr = arr.reshape(3,4);
print(narr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


12. Flatten a 2D array of shape (2, 3) into a 1D array.

In [40]:
arr =np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
newarr = arr.reshape(-1)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


13.Convert a 1D array of 9 elements into a 3x3 square matrix.

In [41]:
arr =np.array([1,2,3,4,5,6,7,8,9])
narr = arr.reshape(3,3);
print(narr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


14.Reshape a 1D array of 20 elements into a 4x5 matrix.

In [43]:
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
narr = arr.reshape(4,5);
print(narr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


15.Transform a 2D array of shape (3, 2) into a 1D array of shape (6,).


In [45]:
arr =np.array([[1,2,3],[4,5,6]])
narr = arr.reshape(6,)
print(narr)

[1 2 3 4 5 6]
