In [ ]:
import numpy as np

**How to create a basic array**

This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [ ]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
#create an array filled with 0’s
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#explicitly specify which data type you want using the dtype keyword
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [ ]:
#Return a new array of given shape and type, filled with fill_value.
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [ ]:
#function empty creates an array whose initial content is random and depends on the state of the memory
np.empty(2)

array([0., 0.])

In [ ]:
# create an array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
#specify the first number, last number, and the step size
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
#create an array with values that are spaced linearly in a specified interval
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

**Adding, removing, and sorting elements**

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [ ]:
# sorting numpy
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

#Broadcasting

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting.

In [ ]:
data = np.array([1, 2, 3, 4])
data * 1.6

array([1.6, 3.2, 4.8, 6.4])

#More useful array operations



In [ ]:
data.max()
data.min()
data.sum()

10